name: accessd
base: core22
version: '1.0'
summary: WiFi Router for Mini PC
description: |
  Turn your mini PC into a WiFi router with hostapd, dnsmasq, and NAT routing.
  Provides a complete routing solution with DHCP, DNS, and wireless access point.

title: AccessD WiFi Router
license: MIT
contact: https://github.com/yourusername/accessd

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  daemon:
    command: bin/nat-daemon
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind
      - network-control
      - firewall-control
      - network-setup-observe
      - network-setup-control

  hostapd:
    command: bin/hostapd-daemon
    daemon: simple
    restart-condition: on-failure
    restart-delay: 10s
    plugs:
      - network
      - network-control
      - firewall-control
      - network-setup-observe
      - network-setup-control

  dnsmasq:
    command: bin/dnsmasq-daemon
    daemon: simple
    restart-condition: on-failure
    restart-delay: 5s
    plugs:
      - network
      - network-bind
      - network-control
    
  configure:
    command: bin/configure
    plugs:
      - network
      - network-control
      
  status:
    command: bin/status
    plugs:
      - network
      - network-control
      - firewall-control

hooks:
  install:
    plugs:
      - network-control
      - firewall-control
  configure:
    plugs:
      - network-control
      - firewall-control

parts:
  hostapd:
    plugin: nil
    stage-packages:
      - hostapd
    override-build: |
      craftctl default
      
  dnsmasq:
    plugin: nil
    stage-packages:
      - dnsmasq
    override-build: |
      craftctl default
      
  network-tools:
    plugin: nil
    stage-packages:
      - iptables
      - iproute2
      - wireless-tools
      - rfkill
      - libatm1
    override-build: |
      craftctl default
      
  scripts:
    plugin: dump
    source: scripts/
    organize:
      '*': bin/
    override-build: |
      rm -rf "$CRAFT_PART_INSTALL"
      mkdir -p "$CRAFT_PART_INSTALL"
      craftctl default
      if [ -d "$CRAFT_PART_INSTALL/bin" ]; then
        find "$CRAFT_PART_INSTALL/bin" -maxdepth 1 -type f -exec chmod +x {} +
      else
        find "$CRAFT_PART_INSTALL" -maxdepth 1 -type f -exec chmod +x {} +
      fi
    stage:
      - bin/*

  templates:
    plugin: dump
    source: templates/
    organize:
      '*': etc/accessd/
